---
title: "Component 2, Stage 2: SPI -> SDG"
output: html_document
---
# Stage 2: SDG ~ SPI (Mediator) + DI 

# Set up and Wrangling 
```{r}
# set working directory
setwd("~/Documents/GitHub/QMSS_Thesis_Sanchez")

#load libraries/packages
source("packages.R")

#load data 
all_data <- read_csv("data/Main CSV Outputs/merged_final_df.csv")

# selecting vars
panel_data <- all_data %>% 
  dplyr::select(country_name, country_code, year, sdg_overall, spi_comp, di_score, log_gdppc, income_level, aut_ep, dem_ep, regch_event, regime_type_2, regime_type_4, elect_dem, lib_dem, part_dem, delib_dem, egal_dem, academ_free) %>% 
  arrange(country_code, year) %>%  # Critical for correct lagging
  filter(year >= 2016)

# Adding has_aut_ep and has_dem_ep for regressing regimes (experienced atleast 1 aut_ep/dem_ep)
panel_data <- panel_data %>%
  # Group by country to check for any event
  group_by(country_code) %>%
  mutate(has_aut_ep = any(aut_ep == 1, na.rm = TRUE)) %>%
  mutate(has_dem_ep = any(dem_ep == 1, na.rm = TRUE)) %>% 
  ungroup() 

# centralized variables for higher-order multicollinearity 
panel_data <- panel_data %>%
  mutate(
    cen_sdg_overall = sdg_overall - mean(sdg_overall, na.rm = TRUE),
    cen_spi_comp = spi_comp - mean(spi_comp, na.rm = TRUE),
    cen_di_score = di_score - mean(di_score, na.rm = TRUE),
    cen_log_gdppc = log_gdppc - mean(log_gdppc, na.rm = TRUE)
  )

panel_data <- panel_data %>% 
# Recoding income_level, split income_level into dummy variables using case_when()
  mutate(income_level_recoded = case_when(
    income_level == "L" ~ 0, # Low-Income
    income_level == "LM" ~ 1, # Lower-Middle-Income
    income_level == "UM" ~ 2, # Upper-Middle-Income
    income_level == "H" ~ 3, # High-Income
    TRUE ~ NA_real_  # Handle any other cases
  )) %>% 
  mutate(income_level_recoded = as.factor(income_level_recoded)) %>% 
  # recoding/factorizing regime_type_2: 0 = Autocracy; 1 = Democracy 
  mutate(regime_type_binary = as.factor(regime_type_2)) %>% 
  # recoding regime_type_4: 0 = Closed Autocracy; 1 = Electoral Autocracy; 2 = Electoral Democracy; 3 = Full Democracy
  mutate(regime_type_categ = as.factor(regime_type_4)) %>% 
  mutate(aut_ep = as.factor(aut_ep), # autocratization episode
         dem_ep = as.factor(dem_ep)) # democratization episode

# year-year lags for FD Models - DF
fd_data <- panel_data %>%
  select(country_code, year, sdg_overall, di_score, spi_comp, log_gdppc, income_level, aut_ep, dem_ep, income_level_recoded, regch_event) %>%
  filter(!is.na(di_score) & !is.na(spi_comp) | !is.na(spi_comp) & !is.na(sdg_overall)) %>% 
  arrange(country_code, year) %>%
  group_by(country_code) %>%
  mutate(
    # first differences for selected variables
    sdg_diff = sdg_overall - dplyr::lag(sdg_overall, n=1),
    di_diff = di_score - dplyr::lag(di_score, n=1),
    spi_diff = spi_comp - dplyr::lag(spi_comp,n=1),
    log_gdppc_diff = log_gdppc - dplyr::lag(log_gdppc, n=1),
    # lagged first differences 
    di_diff_lag1 = dplyr::lag(di_diff, n=1),
    di_diff_lag2 = dplyr::lag(di_diff, n=2),
    spi_diff_lag1 = dplyr::lag(spi_diff, n=1),
    spi_diff_lag2 = dplyr::lag(spi_diff, n=2),
    log_gdppc_diff_lag1 = dplyr::lag(log_gdppc_diff, n=1),
    log_gdppc_diff_lag1 = dplyr::lag(log_gdppc_diff, n=2)
  ) %>%
  ungroup()
```

# 2.1) POLS SDG ~ SPI [Stage 2]
```{r}
ols_sdg_spi <- plm(formula = sdg_overall ~ dplyr::lag(spi_comp,n=1) + dplyr::lag(di_score, n=1) + log_gdppc + income_level_recoded + factor(year), 
               model = "pooling", 
               index = c("country_code", "year"),
               data = panel_data)
summary(ols_sdg_spi, vcov = vcovHC(ols_sdg_spi, cluster = "group", type = "HC1"))

# plot relationship
ggplot(panel_data, aes(x = spi_comp, y = sdg_overall)) + 
  geom_point(color = "steelblue4", size = 1, alpha = 0.65) +
  geom_smooth(method = "lm", 
              se = TRUE, color = "darkgreen", size = 1) +
  labs(
    title = "Effect of SPI Levels on SDG Scores",
    x = "SPI Score (0-100 Scale)",
    y = "SDG Score (0-100 Scale)"
  ) +
  theme_minimal()

# Save to specific folder
#ggsave("figures/sdg_spi_scatterplot.png", Compare_fit, width = #10, height = 6)
```


# 2.2) First Difference [Stage 2]
```{r}
# Outcome: SDG ~ SPI (Y ~ M)
fd_sdg_spi <- plm(
  formula = sdg_overall ~ dplyr::lag(spi_comp,n=1) + dplyr::lag(di_score, n=1) + log_gdppc + income_level_recoded,
  index = c("country_code", "year"),
  data = fd_data, 
  model = "fd"
)
# Country-level custard Robust SEs
summary(fd_sdg_spi, vcov = vcovHC(fd_sdg_spi, cluster = "group", type = "HC1"))
```


# 2.3) Fixed Effects [Stage 2]
```{r}
# Outcome: SDG ~ SPI (Y ~ M)
fe_sdg_spi <- plm(
  sdg_overall ~ dplyr::lag(spi_comp,n=1) + dplyr::lag(di_score, n=1) + log_gdppc + income_level_recoded,
  index = c("country_code", "year"),
  data = panel_data,
  model = "within", #FE
  effect = "twoways"
)
summary(fe_sdg_spi, vcov = vcovHC(fe_sdg_spi, cluster = "group", type = "HC1")) # Robust SEs
```

# Model Selection: Adj. R^2 & AIC/BIC [Stage 2]
```{r}
# AIC/BIC function
source('plm_aic_bic_function.R')

# First difference 
plm_aic_bic(fd_sdg_spi) 

# Fixed Effects 
plm_aic_bic(fe_sdg_spi) 
```


# RESET Test for Misspecification [STAGE 2]
```{r}
ols_sdg_spi <- lm(sdg_overall ~ spi_comp + di_score + log_gdppc + #income_level_recoded + 
                    factor(year), data = panel_data) # regular linear model
fd_sdg_spi <- lm(sdg_overall ~ dplyr::lag(spi_comp, 1) + dplyr::lag(di_diff, 1) + log_gdppc_diff, 
                 #+ income_level_recoded, 
                 data = fd_data)
fe_sdg_spi <- lm(sdg_overall ~ dplyr::lag(spi_comp, 1) + dplyr::lag(di_score, 1) + log_gdppc 
                 #+ income_level_recoded 
                 + factor(year) + factor(country_code), data = panel_data)

# Run RESET tests w/ Robust SEs [Stage 2]
resettest(ols_sdg_spi, power = 2:3, type = "regressor", 
          vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))
resettest(fd_sdg_spi, power = 2:3, type = "regressor",
          vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))
resettest(fe_sdg_spi, power = 2:3, type = "regressor",
          vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))

# Saving results to a dataframe
s2_reset_results <- data.frame(
  model = c("ols_sdg_spi", "fd_sdg_spi", "fe_sdg_spi"),
  F_statistic = c(resettest(ols_sdg_spi, power = 2:3, type = "regressor", 
                             vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))$statistic,
                  resettest(fd_sdg_spi, power = 2:3, type = "regressor",
                             vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))$statistic,
                  resettest(fe_sdg_spi, power = 2:3, type = "regressor",
                             vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))$statistic),
  p_value = c(resettest(ols_sdg_spi, power = 2:3, type = "regressor", 
                        vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))$p.value,
              resettest(fd_sdg_spi, power = 2:3, type = "regressor",
                        vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))$p.value,
              resettest(fe_sdg_spi, power = 2:3, type = "regressor",
                        vcov = function(x) vcovHC(x, cluster = "group", type = "HC1"))$p.value)
)
# Save the results to a CSV file
write.csv(s2_reset_results, file = "output_CSVs/s2_reset_results.csv", row.names = FALSE)
```
