% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Component 2, Direct Effect, SDG \textasciitilde{} DI},
  pdfauthor={Sevastian Sanchez},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Component 2, Direct Effect, SDG \textasciitilde{} DI}
\author{Sevastian Sanchez}
\date{2025-10-13}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}
  \AttributeTok{echo =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{warning =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{message =} \ConstantTok{FALSE}\NormalTok{,}
  \AttributeTok{tidy =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{tidy.opts =} \FunctionTok{list}\NormalTok{(}\AttributeTok{width.cutoff =} \DecValTok{60}\NormalTok{) }
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\section{Set up}\label{set-up}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# set working directory}
\FunctionTok{setwd}\NormalTok{(}\StringTok{"\textasciitilde{}/Documents/GitHub/QMSS\_Thesis\_Sanchez"}\NormalTok{)}

\CommentTok{\# load libraries/packages}
\FunctionTok{source}\NormalTok{(}\StringTok{"packages.R"}\NormalTok{)}

\CommentTok{\# load data}
\FunctionTok{source}\NormalTok{(}\StringTok{"Comp2\_panel\_wrangling.R"}\NormalTok{)}

\NormalTok{panel\_data }\OtherTok{\textless{}{-}}\NormalTok{ panel\_data }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{    dplyr}\SpecialCharTok{::}\FunctionTok{select}\NormalTok{(country\_name, country\_code, year, sdg\_overall,}
\NormalTok{        di\_score, log\_gdppc, income\_level\_recoded) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{    dplyr}\SpecialCharTok{::}\FunctionTok{arrange}\NormalTok{(country\_code, year)}

\CommentTok{\# how many countries}
\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(panel\_data}\SpecialCharTok{$}\NormalTok{country\_code))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 162
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# check dimensions}
\FunctionTok{dim}\NormalTok{(panel\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1296    7
\end{verbatim}

\subsection{Converting to panel data
frame}\label{converting-to-panel-data-frame}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{panel\_data }\OtherTok{\textless{}{-}} \FunctionTok{pdata.frame}\NormalTok{(panel\_data, }\AttributeTok{index =} \FunctionTok{c}\NormalTok{(}\StringTok{"country\_code"}\NormalTok{,}
    \StringTok{"year"}\NormalTok{))}
\FunctionTok{pdim}\NormalTok{(panel\_data)  }\CommentTok{\# check panel dimensions}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Balanced Panel: n = 162, T = 8, N = 1296
\end{verbatim}

\section{Direct Effect: SDG \textasciitilde{}
DI}\label{direct-effect-sdg-di}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Model POLS: Basic FE model with DI as predictor}
\NormalTok{model\_pols }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ sdg\_overall }\SpecialCharTok{\textasciitilde{}}\NormalTok{ di\_score }\SpecialCharTok{+}\NormalTok{ plm}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(di\_score,}
    \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ plm}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(di\_score, }\DecValTok{2}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ log\_gdppc }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year), }\AttributeTok{data =}\NormalTok{ panel\_data,}
    \AttributeTok{model =} \StringTok{"pooling"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(model\_pols, }\AttributeTok{vcov =} \FunctionTok{vcovHC}\NormalTok{(model\_pols, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{,}
    \AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Pooling Model
## 
## Note: Coefficient variance-covariance matrix supplied: vcovHC(model_pols, cluster = "group", type = "HC1")
## 
## Call:
## plm(formula = sdg_overall ~ di_score + plm::lag(di_score, 1) + 
##     plm::lag(di_score, 2) + log_gdppc + factor(year), data = panel_data, 
##     model = "pooling")
## 
## Unbalanced Panel: n = 155, T = 5-6, N = 927
## 
## Residuals:
##      Min.   1st Qu.    Median   3rd Qu.      Max. 
## -14.17492  -3.74040   0.17196   3.93322  14.72078 
## 
## Coefficients:
##                        Estimate Std. Error t-value  Pr(>|t|)    
## (Intercept)           22.663415   3.012444  7.5233 1.274e-13 ***
## di_score               0.677635   0.736976  0.9195    0.3581    
## plm::lag(di_score, 1) -0.279082   0.365461 -0.7636    0.4453    
## plm::lag(di_score, 2)  0.804751   0.923631  0.8713    0.3838    
## log_gdppc              4.291900   0.499021  8.6006 < 2.2e-16 ***
## factor(year)2019       0.460586   0.052433  8.7843 < 2.2e-16 ***
## factor(year)2020       1.186165   0.086048 13.7849 < 2.2e-16 ***
## factor(year)2021       0.962557   0.138003  6.9749 5.857e-12 ***
## factor(year)2022       0.914697   0.145970  6.2663 5.680e-10 ***
## factor(year)2023       1.012996   0.227972  4.4435 9.932e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    91943
## Residual Sum of Squares: 28365
## R-Squared:      0.69149
## Adj. R-Squared: 0.68847
## F-statistic: 70.4589 on 9 and 154 DF, p-value: < 2.22e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Model FD: Basic model with DI as predictor}
\NormalTok{model\_fd }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ sdg\_overall }\SpecialCharTok{\textasciitilde{}}\NormalTok{ di\_score }\SpecialCharTok{+}\NormalTok{ plm}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(di\_score,}
    \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ plm}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(di\_score, }\DecValTok{2}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ log\_gdppc }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year), }\AttributeTok{data =}\NormalTok{ panel\_data,}
    \AttributeTok{model =} \StringTok{"fd"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(model\_fd, }\AttributeTok{vcov =} \FunctionTok{vcovHC}\NormalTok{(model\_fd, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{,}
    \AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Oneway (individual) effect First-Difference Model
## 
## Note: Coefficient variance-covariance matrix supplied: vcovHC(model_fd, cluster = "group", type = "HC1")
## 
## Call:
## plm(formula = sdg_overall ~ di_score + plm::lag(di_score, 1) + 
##     plm::lag(di_score, 2) + log_gdppc + factor(year), data = panel_data, 
##     model = "fd")
## 
## Unbalanced Panel: n = 155, T = 5-6, N = 927
## Observations used in estimation: 772
## 
## Residuals:
##      Min.   1st Qu.    Median   3rd Qu.      Max. 
## -1.700150 -0.285039 -0.037092  0.239273  3.014071 
## 
## Coefficients: (1 dropped because of singularities)
##                        Estimate Std. Error t-value  Pr(>|t|)    
## (Intercept)            0.296270   0.022942 12.9141 < 2.2e-16 ***
## di_score               0.034680   0.090843  0.3818 0.7027498    
## plm::lag(di_score, 1)  0.148369   0.074249  1.9983 0.0460436 *  
## plm::lag(di_score, 2) -0.184427   0.127140 -1.4506 0.1473061    
## log_gdppc             -0.141934   0.284531 -0.4988 0.6180386    
## factor(year)2019       0.093508   0.030233  3.0930 0.0020539 ** 
## factor(year)2020       0.187876   0.056572  3.3210 0.0009396 ***
## factor(year)2021       0.140281   0.041286  3.3978 0.0007146 ***
## factor(year)2022       0.054473   0.043659  1.2477 0.2125289    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    229.84
## Residual Sum of Squares: 221.95
## R-Squared:      0.034338
## Adj. R-Squared: 0.024213
## F-statistic: 3.69084 on 8 and 154 DF, p-value: 0.00057272
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# CI for FD model with Lag2}
\NormalTok{coef }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(model\_fd)}
\NormalTok{se }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vcovHC}\NormalTok{(model\_fd, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{)))  }\CommentTok{\# Get standard errors}
\NormalTok{crit\_value }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =} \FunctionTok{nobs}\NormalTok{(model\_fd) }\SpecialCharTok{{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{coef}\NormalTok{(model\_fd)))}
\NormalTok{ci\_low }\OtherTok{\textless{}{-}}\NormalTok{ coef }\SpecialCharTok{{-}}\NormalTok{ crit\_value }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{ci\_high }\OtherTok{\textless{}{-}}\NormalTok{ coef }\SpecialCharTok{+}\NormalTok{ crit\_value }\SpecialCharTok{*}\NormalTok{ se}
\FunctionTok{cbind}\NormalTok{(ci\_low, ci\_high)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                             ci_low    ci_high
## (Intercept)            0.251234395 0.34130657
## di_score              -0.143651904 0.21301121
## plm::lag(di_score, 1)  0.002611807 0.29412558
## plm::lag(di_score, 2) -0.434012310 0.06515808
## log_gdppc             -0.700491107 0.41662232
## factor(year)2019       0.034159126 0.15285671
## factor(year)2020       0.076820801 0.29893080
## factor(year)2021       0.059233079 0.22132963
## factor(year)2022      -0.031233476 0.14017954
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# joint significance {-} FD}
\FunctionTok{linearHypothesis}\NormalTok{(model\_fd, }\FunctionTok{c}\NormalTok{(}\StringTok{"di\_score = 0"}\NormalTok{, }\StringTok{"plm::lag(di\_score, 1) = 0"}\NormalTok{,}
    \StringTok{"plm::lag(di\_score, 2) = 0"}\NormalTok{), }\AttributeTok{vcov. =} \FunctionTok{vcovHC}\NormalTok{(model\_fd, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{,}
    \AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## di_score = 0
## plm::lag(di_score,0
## plm::lag(di_score, 2) = 0
## 
## Model 1: restricted model
## Model 2: sdg_overall ~ di_score + plm::lag(di_score, 1) + plm::lag(di_score, 
##     2) + log_gdppc + factor(year)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df  Chisq Pr(>Chisq)
## 1    766                     
## 2    763  3 4.3277     0.2282
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ensure correct names names(coef(model\_fd))}

\CommentTok{\# cumulative effect {-} FD}
\FunctionTok{linearHypothesis}\NormalTok{(model\_fd, }\FunctionTok{c}\NormalTok{(}\StringTok{"di\_score + plm::lag(di\_score, 1) + plm::lag(di\_score, 2) = 0"}\NormalTok{),}
    \AttributeTok{vcov. =} \FunctionTok{vcovHC}\NormalTok{(model\_fd, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## di_score  + plm::lag(di_score,1 plm::lag(di_score, 2) = 0
## 
## Model 1: restricted model
## Model 2: sdg_overall ~ di_score + plm::lag(di_score, 1) + plm::lag(di_score, 
##     2) + log_gdppc + factor(year)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df Chisq Pr(>Chisq)
## 1    764                    
## 2    763  1 2e-04     0.9879
\end{verbatim}

\textbf{Results:} The joint significance tests for FD show no evidence
that DI variables are jointly significant in explaining changes in SDG
overall scores (Chisq = 4.3277, p = 0.2282). This suggests that DI may
not have a meaningful immediate impact on SDG outcomes when considering
both current and lagged effects.

In terms of \emph{cumulative impact}, based on the FD model and panel
data, showed no evidence of cumulative total impacts of changes in
di\_score (at current, lag 1, or lag 2) on SPI ---over these periods
(stat = 2e-04, p = 0.9879).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Model FE: Basic model with DI as predictor}
\NormalTok{model\_fe }\OtherTok{\textless{}{-}} \FunctionTok{plm}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ sdg\_overall }\SpecialCharTok{\textasciitilde{}}\NormalTok{ di\_score }\SpecialCharTok{+}\NormalTok{ plm}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(di\_score,}
    \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ plm}\SpecialCharTok{::}\FunctionTok{lag}\NormalTok{(di\_score, }\DecValTok{2}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ log\_gdppc }\SpecialCharTok{+} \FunctionTok{factor}\NormalTok{(year), }\AttributeTok{data =}\NormalTok{ panel\_data,}
    \AttributeTok{model =} \StringTok{"within"}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(model\_fe, }\AttributeTok{vcov =} \FunctionTok{vcovHC}\NormalTok{(model\_fe, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{,}
    \AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Oneway (individual) effect Within Model
## 
## Note: Coefficient variance-covariance matrix supplied: vcovHC(model_fe, cluster = "group", type = "HC1")
## 
## Call:
## plm(formula = sdg_overall ~ di_score + plm::lag(di_score, 1) + 
##     plm::lag(di_score, 2) + log_gdppc + factor(year), data = panel_data, 
##     model = "within")
## 
## Unbalanced Panel: n = 155, T = 5-6, N = 927
## 
## Residuals:
##       Min.    1st Qu.     Median    3rd Qu.       Max. 
## -2.4658794 -0.2345215  0.0066089  0.2299494  3.2482893 
## 
## Coefficients:
##                         Estimate Std. Error t-value Pr(>|t|)    
## di_score               0.0962806  0.0803768  1.1979  0.23134    
## plm::lag(di_score, 1)  0.1669276  0.0996600  1.6750  0.09435 .  
## plm::lag(di_score, 2) -0.2010186  0.1281638 -1.5685  0.11719    
## log_gdppc              0.0034893  0.3548360  0.0098  0.99216    
## factor(year)2019       0.3908982  0.0388479 10.0623  < 2e-16 ***
## factor(year)2020       0.7971106  0.0656768 12.1369  < 2e-16 ***
## factor(year)2021       1.0350451  0.0686708 15.0726  < 2e-16 ***
## factor(year)2022       1.2357207  0.0869007 14.2199  < 2e-16 ***
## factor(year)2023       1.4593392  0.1162733 12.5509  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Total Sum of Squares:    441.14
## Residual Sum of Squares: 216.25
## R-Squared:      0.50979
## Adj. R-Squared: 0.40507
## F-statistic: 37.407 on 9 and 154 DF, p-value: < 2.22e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# CI for FE model with Lag2}
\NormalTok{coef }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(model\_fe)}
\NormalTok{se }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{diag}\NormalTok{(}\FunctionTok{vcovHC}\NormalTok{(model\_fe, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{)))  }\CommentTok{\# Get standard errors}
\NormalTok{crit\_value }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\AttributeTok{df =} \FunctionTok{nobs}\NormalTok{(model\_fe) }\SpecialCharTok{{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{coef}\NormalTok{(model\_fe)))}
\NormalTok{ci\_low }\OtherTok{\textless{}{-}}\NormalTok{ coef }\SpecialCharTok{{-}}\NormalTok{ crit\_value }\SpecialCharTok{*}\NormalTok{ se}
\NormalTok{ci\_high }\OtherTok{\textless{}{-}}\NormalTok{ coef }\SpecialCharTok{+}\NormalTok{ crit\_value }\SpecialCharTok{*}\NormalTok{ se}
\FunctionTok{cbind}\NormalTok{(ci\_low, ci\_high)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                            ci_low    ci_high
## di_score              -0.06146310 0.25402421
## plm::lag(di_score, 1) -0.02866023 0.36251550
## plm::lag(di_score, 2) -0.45254670 0.05050942
## log_gdppc             -0.69289461 0.69987320
## factor(year)2019       0.31465719 0.46713925
## factor(year)2020       0.66821658 0.92600466
## factor(year)2021       0.90027518 1.16981503
## factor(year)2022       1.06517352 1.40626792
## factor(year)2023       1.23114686 1.68753159
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# joint significance {-} FE}
\FunctionTok{linearHypothesis}\NormalTok{(model\_fe, }\FunctionTok{c}\NormalTok{(}\StringTok{"di\_score = 0"}\NormalTok{, }\StringTok{"plm::lag(di\_score, 1) = 0"}\NormalTok{,}
    \StringTok{"plm::lag(di\_score, 2) = 0"}\NormalTok{), }\AttributeTok{vcov. =} \FunctionTok{vcovHC}\NormalTok{(model\_fe, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{,}
    \AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## di_score = 0
## plm::lag(di_score,0
## plm::lag(di_score, 2) = 0
## 
## Model 1: restricted model
## Model 2: sdg_overall ~ di_score + plm::lag(di_score, 1) + plm::lag(di_score, 
##     2) + log_gdppc + factor(year)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df  Chisq Pr(>Chisq)  
## 1    766                       
## 2    763  3 7.8736     0.0487 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ensure correct names names(coef(model\_fe))}

\CommentTok{\# cumulative effect {-} FE}
\FunctionTok{linearHypothesis}\NormalTok{(model\_fe, }\FunctionTok{c}\NormalTok{(}\StringTok{"di\_score + plm::lag(di\_score, 1) + plm::lag(di\_score, 2) = 0"}\NormalTok{),}
    \AttributeTok{vcov. =} \FunctionTok{vcovHC}\NormalTok{(model\_fe, }\AttributeTok{cluster =} \StringTok{"group"}\NormalTok{, }\AttributeTok{type =} \StringTok{"HC1"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Linear hypothesis test:
## di_score  + plm::lag(di_score,1 plm::lag(di_score, 2) = 0
## 
## Model 1: restricted model
## Model 2: sdg_overall ~ di_score + plm::lag(di_score, 1) + plm::lag(di_score, 
##     2) + log_gdppc + factor(year)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df  Chisq Pr(>Chisq)
## 1    764                     
## 2    763  1 0.3742     0.5407
\end{verbatim}

\textbf{Result:} The joint significance tests for FE show that the DI
variables are jointly significant in explaining changes in SDG overall
scores (Chisq = 7.8736, p = 0.0487). This suggests that DI has a
meaningful incremental impact on SDG outcomes when considering both
current and lagged effects.

In terms of \emph{cumulative impact}, based on the FE model and panel
data, results detected a total impact of changes in di\_score (at
current, lag 1, or lag 2) on SPI ---over these periods (stat = 0.3742, p
= 0.5407)

\end{document}
