---
title: "SPI~SDG+DI"
output: html_document
---
# TESTING REVERSE CAUSALITY: SPI AS DV, SDG AND DI AS IVS

# Set up and Wrangling 
```{r}
# set working directory
setwd("~/Documents/GitHub/QMSS_Thesis_Sanchez")

#load libraries/packages
source("packages.R")

# load data
source("Comp2_panel_wrangling.R")
```

# Model 1: SPI ~ SDG + DI + Controls
```{r}
model1 <- plm(spi_comp ~ sdg_overall + dplyr::lag(sdg_overall, 1) + dplyr::lag(sdg_overall, 2) + di_score + dplyr::lag(di_score, 1) + dplyr::lag(di_score, 2) + log_gdppc + income_level_recoded, 
              data = panel_data, 
              model = "within", 
              index = c("country_code", "year"),
              effect = "twoways")
summary(model1)
summary(model1, vcov = vcovHC(model1, cluster = "group", type = "HC1"))
```

# Model 2: SDG ~ SPI + DI + Controls
```{r}
model2 <- plm(sdg_overall ~ spi_comp + dplyr::lag(spi_comp, 1) + dplyr::lag(spi_comp, 2) + di_score + dplyr::lag(di_score, 1) + dplyr::lag(di_score, 2) + log_gdppc + income_level_recoded, 
              data = panel_data, 
              model = "within", 
              index = c("country_code", "year"),
              effect = "twoways")
summary(model2)
summary(model2, vcov = vcovHC(model2, cluster = "group", type = "HC1"))
```

# Model Observations 
Function that extracts model data for plm models
```{r}
# load the extract_plm_data function
source("functions/extract_plm_data_function.R")

model1_data <- extract_plm_data(model1)
model2_data <- extract_plm_data(model2)
```

