---
title: "distributed_lags_testing"
author: "Sevastian Sanchez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data 
```{r}
#load libraries 
source("packages.R")

#read merged_df csv
fd_fe_data <- read_csv("data/Main CSV Outputs/merged_final_df.csv")

#selecting vars
fd_fe_data <- fd_fe_data %>% 
  dplyr::select(country_code, year, sdg_overall, spi_comp, di_score, aut_ep, dem_ep, elect_dem, lib_dem, part_dem, delib_dem, egal_dem, academ_free, income_level, income_level_lab, log_gdppc, population) %>% 
  arrange(country_code, year) %>%  # Critical for correct lagging
  filter(year >= 2016)

# adding has_aut_ep and has_dem_ep for regressing regimes (experienced atleast 1 aut_ep/dem_ep)
fd_fe_data <- fd_fe_data %>%
  # Group by country to check for any event
  group_by(country_code) %>%
  mutate(has_aut_ep = any(aut_ep == 1, na.rm = TRUE)) %>%
  mutate(has_dem_ep = any(dem_ep == 1, na.rm = TRUE)) %>% 
  ungroup() 
```

# Stage 1: Comparing models (M ~ X)
```{r}
###### SPI ~ DI (M ~ X) ######
fe_spi_di1 <- plm(
  formula = spi_comp ~ di_score + log_gdppc + factor(year),
  index = c("country_code", "year"),
  data = fd_fe_data,
  model = "within" 
)

###### SPI ~ DI (M ~ X) ###### LAG 
fe_spi_di_lag2 <- plm(
  formula = spi_comp ~ lag(di_score, 1) + log_gdppc + factor(year),
  index = c("country_code", "year"),
  data = fd_fe_data,
  model = "within" 
)

###### SPI ~ DI (M ~ X) ###### LAG + current 
fe_spi_di_lag3 <- plm(
  formula = spi_comp ~ di_score + lag(di_score, 1) + log_gdppc + factor(year),
  index = c("country_code", "year"),
  data = fd_fe_data,
  model = "within" 
)

source("functions/plm_aic_bic.R")

#models 
fe_spi_di1
fe_spi_di_lag2
fe_spi_di_lag3
fe_spi_di_lag4

# comparing model fit
plm_aic_bic(fe_spi_di1)
plm_aic_bic(fe_spi_di_lag2)
plm_aic_bic(fe_spi_di_lag3)
```


# Stage 2: Comparing Models (Y ~ M + X)
```{r}
###### SDG ~ SPI (Y ~ M) ###### 1. None
fe_sdg_spi1 <- plm(
  sdg_overall ~ spi_comp + di_score + log_gdppc + factor(year),
  index = c("country_code", "year"),
  data = fd_fe_data,
  effect = "twoways",
  model = "within" 
)

###### SDG ~ SPI (Y ~ M) ###### 2. LAG 
fe_sdg_spi_lag2 <- plm(
  sdg_overall ~ spi_comp + lag(di_score, 1) + log_gdppc + factor(year),
  index = c("country_code", "year"),
  data = fd_fe_data,
  effect = "twoways", 
  model = "within"
)

###### SDG ~ SPI (Y ~ M) ###### 3. LAGS 
fe_sdg_spi_lag3 <- plm(
  sdg_overall ~ lag(spi_comp, 1) + lag(di_score, 1) + log_gdppc + factor(year),
  index = c("country_code", "year"),
  data = fd_fe_data,
  effect = "twoways",
  model = "within"
)

#Models 
fe_sdg_spi1
fe_sdg_spi_lag2
fe_sdg_spi_lag3

# Comparing fit 
plm_aic_bic(fe_sdg_spi1)
plm_aic_bic(fe_sdg_spi_lag2)
plm_aic_bic(fe_sdg_spi_lag3)
```


