---
title: "H4_SDG~DI+SPI"
output: html_document
---

```{r}
# set working directory
setwd("~/Documents/GitHub/QMSS_Thesis_Sanchez")

#load libraries/packages
source("packages.R")

# load data
source("Comp2_panel_wrangling.R")
```

# Define Group Variable
```{r}
# Define the group variable based on regime stability
group <- 
  # panel_data$has_aut_ep == 1
  # panel_data$has_dem_ep == 1 
  # panel_data$has_neither == 1
  # panel_data$autocratized == 1 
  # panel_data$democratized == 1 
  # panel_data$stable == 1
```

# Baseline SDG and DI Relationship
```{r}
# baseline model
FE_all <- plm(formula = sdg_overall ~ di_score + dplyr::lag(di_score, 1) + dplyr::lag(di_score, 2) + log_gdppc,
              model = "within", 
              index = c("country_code", "year"),
              data = panel_data, 
              subset = group, # modifying based on regime stability
              effect = "twoways")
summary(FE_all)
summary(FE_all, vcov = vcovHC(FE_all, cluster = "group", type = "HC1"))
```

# SDG and DI Relationship + Adding SPI
```{r}
# baseline model
FE_all <- plm(formula = sdg_overall ~ spi_comp + dplyr::lag(spi_comp, 1) + dplyr::lag(spi_comp, 2) + di_score + dplyr::lag(di_score, 1) + dplyr::lag(di_score, 2) + log_gdppc,
              model = "within", 
              index = c("country_code", "year"),
              data = panel_data, 
              subset = group, # modifying based on regime stability
              effect = "twoways")
summary(FE_all)
summary(FE_all, vcov = vcovHC(FE_all, cluster = "group", type = "HC1"))
```